name: hello-world
on: push
jobs:
   my-job:
      runs-on: ubuntu-latest
      steps:
         - name: my-steps
           run: echo "hello worled"
   my-job2:
       needs: my-job
       runs-on: ubuntu-latest
       steps:
           - name: my-steps
             run: echo "step2 osama"
           
